In [53]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, classification_report

In [43]:
df_train = pd.read_csv('../data/raw/train.csv', index_col=0)
df_test = pd.read_csv('../data/raw/train.csv', index_col=0)
df_train

,resolution,brand_name,description,name_rus,CommercialTypeName4,rating_1_count,rating_2_count,rating_3_count,rating_4_count,rating_5_count,...,ExemplarReturnedCountTotal30,ExemplarReturnedCountTotal90,ExemplarReturnedValueTotal7,ExemplarReturnedValueTotal30,ExemplarReturnedValueTotal90,ItemVarietyCount,ItemAvailableCount,seller_time_alive,ItemID,SellerID
id,,,,,,,,,,,,,,,,,,,,,
159385,0,ACTRUM,"Мешки пылесборники для пылесоса PHILIPS, 10 шт...","Мешки для пылесоса PHILIPS TRIATLON, синтетиче...",Пылесборник,6.0,4.0,4.0,3.0,32.0,...,11.0,50.0,730.171845,896.528847,1043.118191,1.0,1.0,1860.0,78312,1218
288616,0,Red Line,Защитная силиконовая крышка обьектива GoPro He...,Защитная крышка Redline на экшн-камеру GoPro (...,Крышка для объектива,NaN,NaN,NaN,NaN,NaN,...,26.0,54.0,993.043882,1137.421611,1188.608000,1.0,1.0,1757.0,141999,1374
108090,0,Talwar Brothers,Плоский медиатор из кости толщиной 0.6 мм<br/>...,Медиатор для гитары Acura GP-PB6,Аксессуар для музыкального инструмента,0.0,0.0,1.0,0.0,1.0,...,16.0,34.0,800.822138,1174.069505,1224.798286,1.0,1.0,1722.0,53306,1448
415607,0,NaN,"Игра Sonic Frontiers для PlayStation 5, русски...","Игра Sonic Frontiers для PlayStation 5, русски...",Видеоигра,NaN,NaN,NaN,NaN,NaN,...,3.0,6.0,0.000000,913.530121,982.789171,3.0,3.0,1692.0,202599,715
332391,0,NaN,Disney Classic Games: Aladdin and The Lion Kin...,"Игра Aladdin and Lion King (PlayStation 4, анг...",Видеоигра,1.0,0.0,0.0,0.0,0.0,...,3.0,6.0,0.000000,913.542170,982.783783,3.0,3.0,1692.0,163725,715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159865,0,Tefal,Парогенератор Tefal Express Vision SV8152E0 об...,Парогенератор Tefal Express Vision SV8152E0 с ...,Паровая станция,4.0,1.0,0.0,6.0,60.0,...,1306.0,3287.0,1411.575785,1562.870338,1659.098176,1.0,1.0,617.0,78564,1425
299636,0,Dyson,Выпрямитель для волос Dyson Airstrait<br/><br/...,Выпрямитель Dyson Airstrait HT01 Nickel / Сopper,Выпрямитель для волос Dyson,0.0,0.0,0.0,1.0,31.0,...,8.0,14.0,1209.998085,1304.055594,1360.362870,1.0,1.0,789.0,147429,1220
24145,0,Weissgauff,Настольная компактная посудомоечная машина Wei...,Weissgauff Посудомоечная машина настольная ком...,Посудомоечная машина компактная,1.0,1.0,1.0,0.0,27.0,...,159.0,382.0,1339.132808,1477.981760,1582.208540,1.0,1.0,533.0,12216,3188
51939,1,Xiaomi,Беспроводные наушники Redmi Buds 4 Lite Молоде...,Наушники Redmi Buds 4 Lite Black,Наушники TWS,55.0,30.0,27.0,21.0,72.0,...,127.0,407.0,1001.608687,1163.593791,1289.893002,1.0,1.0,295.0,25909,4812
104566,0,HUAYU,Пульт для ресивера МТС благодаря своей простот...,Пульт для цифровой приставки ТВ МТС AVIT S2-39...,Универсальный пульт для электроники,45.0,16.0,34.0,38.0,733.0,...,979.0,2534.0,1133.370827,1286.200238,1391.169105,1.0,1.0,1030.0,51594,2249

In [44]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 197198 entries, 159385 to 104566
Data columns (total 44 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   resolution                    197198 non-null  int64
 1   brand_name                    116667 non-null  object
 2   description                   171138 non-null  object
 3   name_rus                      197198 non-null  object
 4   CommercialTypeName4           197198 non-null  object
 5   rating_1_count                47193 non-null   float64
 6   rating_2_count                47193 non-null   float64
 7   rating_3_count                47193 non-null   float64
 8   rating_4_count                47193 non-null   float64
 9   rating_5_count                47193 non-null   float64
 10  comments_published_count      47193 non-null   float64
 11  photos_published_count        47193 non-null   float64
 12  videos_published_count        47193 non-null   float64
 13  PriceDiscounted               197198 non-null  float64
 14  item_time_alive               197198 non-null  int64
 15  item_count_fake_returns7      197198 non-null  int64
 16  item_count_fake_returns30     197198 non-null  int64
 17  item_count_fake_returns90     197198 non-null  int64
 18  item_count_sales7             197198 non-null  int64
 19  item_count_sales30            197198 non-null  int64
 20  item_count_sales90            197198 non-null  int64
 21  item_count_returns7           197198 non-null  int64
 22  item_count_returns30          197198 non-null  int64
 23  item_count_returns90          197198 non-null  int64
 24  GmvTotal7                     187007 non-null  float64
 25  GmvTotal30                    189268 non-null  float64
 26  GmvTotal90                    189791 non-null  float64
 27  ExemplarAcceptedCountTotal7   187007 non-null  float64
 28  ExemplarAcceptedCountTotal30  189268 non-null  float64
 29  ExemplarAcceptedCountTotal90  189791 non-null  float64
 30  OrderAcceptedCountTotal7      186797 non-null  float64
 31  OrderAcceptedCountTotal30     189038 non-null  float64
 32  OrderAcceptedCountTotal90     189681 non-null  float64
 33  ExemplarReturnedCountTotal7   187007 non-null  float64
 34  ExemplarReturnedCountTotal30  189268 non-null  float64
 35  ExemplarReturnedCountTotal90  189791 non-null  float64
 36  ExemplarReturnedValueTotal7   187007 non-null  float64
 37  ExemplarReturnedValueTotal30  189268 non-null  float64
 38  ExemplarReturnedValueTotal90  189791 non-null  float64
 39  ItemVarietyCount              196201 non-null  float64
 40  ItemAvailableCount            196201 non-null  float64
 41  seller_time_alive             197198 non-null  float64
 42  ItemID                        197198 non-null  int64
 43  SellerID                      197198 non-null  int64
dtypes: float64(27), int64(13), object(4)
memory usage: 67.7+ MB

In [45]:
df_train.describe()

,resolution,rating_1_count,rating_2_count,rating_3_count,rating_4_count,rating_5_count,comments_published_count,photos_published_count,videos_published_count,PriceDiscounted,...,ExemplarReturnedCountTotal30,ExemplarReturnedCountTotal90,ExemplarReturnedValueTotal7,ExemplarReturnedValueTotal30,ExemplarReturnedValueTotal90,ItemVarietyCount,ItemAvailableCount,seller_time_alive,ItemID,SellerID
count,197198.000000,47193.000000,47193.000000,47193.000000,47193.000000,47193.000000,47193.000000,47193.000000,47193.000000,197198.000000,...,189268.000000,189791.000000,187007.000000,189268.000000,189791.000000,196201.000000,196201.000000,197198.000000,197198.000000,197198.000000
mean,0.066187,2.048355,0.594876,1.109932,1.253067,13.446274,9.519505,4.412222,0.482699,758.971530,...,51.802196,147.169818,701.520465,905.735423,1025.111018,98.790485,98.732489,684.575827,110563.014001,1504.121553
std,0.248610,13.767362,3.398610,6.044903,6.175065,63.103940,46.637693,18.477008,3.595718,155.940582,...,164.435978,511.811000,413.671912,374.229445,360.664928,245.133031,245.151594,498.399100,63773.111390,2256.212708
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,651.081516,...,3.000000,9.000000,611.486957,858.718884,968.864810,2.000000,2.000000,262.000000,55220.250000,157.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,736.695421,...,16.000000,45.000000,856.211201,1008.683523,1116.673313,7.000000,7.000000,607.000000,110732.500000,514.000000
75%,0.000000,1.000000,0.000000,1.000000,1.000000,7.000000,4.000000,3.000000,0.000000,827.955170,...,52.000000,143.000000,990.670761,1131.163329,1229.895511,58.000000,58.000000,1058.000000,165852.750000,1723.000000
max,1.000000,1007.000000,199.000000,329.000000,518.000000,4465.000000,1753.000000,1035.000000,241.000000,1816.563093,...,55681.000000,181600.000000,1663.665513,1807.589625,1914.000284,1548.000000,1548.000000,2265.000000,220806.000000,12508.000000

In [46]:
df_train.isna().sum()

resolution                           0
brand_name                       80531
description                      26060
name_rus                             0
CommercialTypeName4                  0
rating_1_count                  150005
rating_2_count                  150005
rating_3_count                  150005
rating_4_count                  150005
rating_5_count                  150005
comments_published_count        150005
photos_published_count          150005
videos_published_count          150005
PriceDiscounted                      0
item_time_alive                      0
item_count_fake_returns7             0
item_count_fake_returns30            0
item_count_fake_returns90            0
item_count_sales7                    0
item_count_sales30                   0
item_count_sales90                   0
item_count_returns7                  0
item_count_returns30                 0
item_count_returns90                 0
GmvTotal7                        10191
GmvTotal30                        7930
GmvTotal90                        7407
ExemplarAcceptedCountTotal7      10191
ExemplarAcceptedCountTotal30      7930
ExemplarAcceptedCountTotal90      7407
OrderAcceptedCountTotal7         10401
OrderAcceptedCountTotal30         8160
OrderAcceptedCountTotal90         7517
ExemplarReturnedCountTotal7      10191
ExemplarReturnedCountTotal30      7930
ExemplarReturnedCountTotal90      7407
ExemplarReturnedValueTotal7      10191
ExemplarReturnedValueTotal30      7930
ExemplarReturnedValueTotal90      7407
ItemVarietyCount                   997
ItemAvailableCount                 997
seller_time_alive                    0
ItemID                               0
SellerID                             0
dtype: int64

In [47]:
numeric_cols = df_train.select_dtypes(include=[np.number]).columns
df_train[numeric_cols] = df_train[numeric_cols].fillna(df_train[numeric_cols].median())

numeric_cols = df_test.select_dtypes(include=[np.number]).columns
df_test[numeric_cols] = df_test[numeric_cols].fillna(df_test[numeric_cols].median())

In [48]:
numeric_columns = df_train.select_dtypes(include=[np.number]).columns.tolist()
numeric_columns = [col for col in numeric_columns if col != 'resolution']

In [50]:
X_train = df_train[numeric_columns].fillna(0)
y_train = df_train['resolution']
X_test = df_test[numeric_columns].fillna(0)

In [ ]:

X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42, stratify=y_train
)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_split, y_train_split)

Validation accuracy: 0.9658
Classification report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     36830
           1       0.89      0.55      0.68      2610

    accuracy                           0.97     39440
   macro avg       0.93      0.77      0.83     39440
weighted avg       0.96      0.97      0.96     39440

In [ ]:
val_pred = model.predict(X_val_split)
val_accuracy = f1_score(y_val_split, val_pred)

print(f"Validation accuracy: {val_accuracy:.4f}")
print("Classification report:")
print(classification_report(y_val_split, val_pred))
print()

Validation accuracy: 0.6792
Classification report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     36830
           1       0.89      0.55      0.68      2610

    accuracy                           0.97     39440
   macro avg       0.93      0.77      0.83     39440
weighted avg       0.96      0.97      0.96     39440

In [59]:
import lightgbm as lgb

# Настройка для максимальной скорости
params = {
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': 'binary_error',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': -1,
    'n_jobs': -1,  # использовать все ядра
}

train_data = lgb.Dataset(X_train, label=y_train)

# Обучение
model = lgb.train(
    params,
    train_data,
    num_boost_round=1000,
)

In [ ]:
val_pred = 1*(val_pred>.5)

array([0, 0, 0, ..., 0, 0, 0], shape=(39440,))

In [70]:
val_pred = model.predict(X_val_split)
val_pred1 = 1*(val_pred>.5)
val_accuracy = f1_score(y_val_split, val_pred1)

print(f"Validation accuracy: {val_accuracy:.4f}")
print("Classification report:")
print(classification_report(y_val_split, val_pred1))
print()

Validation accuracy: 0.7678
Classification report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     36830
           1       0.94      0.65      0.77      2610

    accuracy                           0.97     39440
   macro avg       0.96      0.82      0.88     39440
weighted avg       0.97      0.97      0.97     39440